name: Continuous Integration

on:
  push:
    branches:
    - main

  pull_request:
    branches:
    - main


jobs:
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
  build-and-test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: lints
    env:
      CARGO_NET_GIT_FETCH_WITH_CLI: true
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      # - run: |
      #     eval `ssh-agent -s`
      #     wc -lc  <<< ${{ secrets.SSH_PRIVATE_KEY }}
      #     ssh-add - <<< ${{ secrets.SSH_PRIVATE_KEY }}
      #     cargo test --all -- --nocapture

      - run: |
          git config --global credential.helper store
          git config --global credential.https://github.com.username=x-access-token
          git config --global credential.https://github.com.helper '!f() { test "$1" = get && echo password="$GITHUB_TOKEN"; }; f'

          # echo "https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
          ls -la

      - run: GIT_TRACE=1 cargo test --all -- --nocapture
